/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FocusTrap {
        "state": any;
    }
    interface MyComponent {
    }
    interface NestedComponent {
        "state": any;
    }
}
declare global {
    interface HTMLFocusTrapElement extends Components.FocusTrap, HTMLStencilElement {
    }
    var HTMLFocusTrapElement: {
        prototype: HTMLFocusTrapElement;
        new (): HTMLFocusTrapElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNestedComponentElement extends Components.NestedComponent, HTMLStencilElement {
    }
    var HTMLNestedComponentElement: {
        prototype: HTMLNestedComponentElement;
        new (): HTMLNestedComponentElement;
    };
    interface HTMLElementTagNameMap {
        "focus-trap": HTMLFocusTrapElement;
        "my-component": HTMLMyComponentElement;
        "nested-component": HTMLNestedComponentElement;
    }
}
declare namespace LocalJSX {
    interface FocusTrap {
        "state"?: any;
    }
    interface MyComponent {
    }
    interface NestedComponent {
        "state"?: any;
    }
    interface IntrinsicElements {
        "focus-trap": FocusTrap;
        "my-component": MyComponent;
        "nested-component": NestedComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "focus-trap": LocalJSX.FocusTrap & JSXBase.HTMLAttributes<HTMLFocusTrapElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "nested-component": LocalJSX.NestedComponent & JSXBase.HTMLAttributes<HTMLNestedComponentElement>;
        }
    }
}
